[server]
headless = false
runOnSave = true
port = 8501
enableXsrfProtection = false
enableCORS = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[global]
developmentMode = false
showWarningOnDirectExecution = false
disableWatchdogWarning = true